name: CI Pipeline  # Nom du workflow

on:
  push:  # Exécution du pipeline à chaque push
  pull_request:  # Exécution sur chaque pull request

jobs:
  test:
    runs-on: ubuntu-latest  # Utilisation de la dernière version d'Ubuntu
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]  # Exécution des tests sur 2 versions de Python
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Récupère le code du repo GitHub

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4  # Installe Python dans l'environnement
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Installe les dépendances nécessaires

      - name: Run tests
        run: python -m pytest  # Exécute les tests avec pytest

  notify:
    needs: [test]  # Cette étape s'exécute après les tests
    runs-on: ubuntu-latest
    steps:
      - name: Simulated Slack Notification
        run: echo "Notifying Slack... (simulation)"  # Simulation d'une notification
